global:
  resolve_timeout: 1m

route:
  receiver: alltoken-dashboard
  group_by: [alertname, severity, channel_id]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 30m

receivers:
  - name: alltoken-dashboard
